zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tfm-tracing-server-service:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://tfm-discovery-server-service:8761/eureka/
  # Al desplegar en kubernates en eureka se registra el nombre de los PODs y luego no se pueden resolver.
  # El DNS de kubernetes KubeDNS registra el nombre del servicio (y los asocia a los PODs)
  # Activado registro por IP
  instance:
    preferIpAddress: true