spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tfm-tracing-server-service:9411
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://tfm-discovery-server-service:8761/eureka/
  # Al desplegar en kubernates en eureka se registra el nombre de los PODs y luego no se pueden resolver.
  # El DNS de kubernetes KubeDNS registra el nombre del servicio (y los asocia a los PODs)
  # Activado registro por IP
  instance:
    preferIpAddress: true
